version: '3.6'
services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    volumes:
      - ./test:/addepar/test:ro
      - ./source:/source:ro
      - ./artifacts:/artifacts
      -  /etc/localtime:/etc/localtime:ro